### PR TITLE
update to 0.4 and get rid of dep warnings

### PR DESCRIPTION
**Pull request by Evizero**
I updated the code to get rid of the warnings and the compat dependency. On the next tag you should increase the `:minor` version

As a side note: are you still interested in maintaining this package? This is a very useful package and you could consider moving it to [JuliaML](https://github.com/JuliaML). I'd be happy to take over maintenance / documentation and such.

### CODE REVIEW

**Comment by IshitaTakeshi** [comment]
Thanks for updating and the commit.

I'm still interested in maintaining this package, but I have some prior works.
I'd be glad if you fork and maintain this in JuliaML.

**Comment by Evizero** [comment]
Given that you are pretty quick to respond I am ok with just doing updates via pull requests to your repo.

Could you go ahead and tag a new `:minor` version to METADATA?

**Comment by IshitaTakeshi** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/4096

**Comment by Evizero** [comment]
Thanks! By the way, if you don't mind then I will reorganize and document the code a little to be in line with the typical Julia conventions.

**Pull request merged**
