### PR TITLE
Cleanup code. Remove global variable and closure

### PR DESCRIPTION
**Pull request by Evizero**
Hey!

I got rid of the closure and the dependency on the global variable. Besides being less error prone, this should in theory also improve performance, but I didn't test that yet. I also fixed a little bug in the tests

### CODE REVIEW

**Comment by IshitaTakeshi** [comment]
I'm busy now. I think I can review this tomorrow.

**Comment by Evizero** [comment]
Thanks! Don't feel pressured by me. Take your time. A few days is a reasonable and common response time to pull requests. I am happy to be working with you.

**Comment by Evizero** [comment]
any news on this?

**Comment by IshitaTakeshi** [comment]
Sorry for being late. I was in a competition.
I just checked the code. It is a very good idea to determine whether the dimension is given or not by a type variable. Tests seems work well. I can merge it soon.

**Comment by IshitaTakeshi** [comment]
Merged

**Comment by Evizero** [comment]
Thanks! Hope the competition went well!

**Pull request merged**
